# RustDesk Server K3S
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rds
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      rds: web
  template:
    metadata:
      labels:
        rds: web
    spec:
      containers:
      - name: rdserver
        image: rustdesk/rustdesk-server-s6:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: rds
  namespace: default
spec:
  type: NodePort
  selector:
    rds: web
  ports:
  - port: 21115
    name: svc0
    protocol: TCP
    targetPort: 21115
    nodePort: 21115
  - port: 21116
    name: access
    protocol: TCP
    targetPort: 21116
    nodePort: 21116
  - port: 21116
    name: accessudp
    protocol: UDP
    targetPort: 21116
    nodePort: 21116
  - port: 21117
    name: svc
    protocol: TCP
    targetPort: 21117
    nodePort: 21117
  - port: 21118
    name: svc2
    protocol: TCP
    targetPort: 21118
    nodePort: 21118
  - port: 21119
    name: svc3
    protocol: TCP
    targetPort: 21119
    nodePort: 21119
